### ISSUE TITLE
Unable to Set Up Configuration

### ISSUE THREAD

**Issue by zhijianglee** [snehaljha/local-tomcat#11]
Well, I must say that the guide here is really half hanging

I have created settings.json in the root folder

{
    "local-tomcat.tomcatInstances": [
        {
            "name": "Tomcat 1",
            "catalinaHome":"C:/Users/xxxxxx/goldenversions/apache-tomcat-10.1.5",
            "deploymentPort": 8080
        }
    ],
    "local-tomcat.warDir": "target"
}

When run Verify tomcat I am still getting No Tomcat instances configured

**Comment by Huindungyi** [comment]
I had the same issue and it still is. Maybe it should be deprecated by now.

**Comment by snehaljha** [comment]
Can you share me the content of the directory you've configured?

Also, it's based on file system so it's important to have presence of catalina.sh/catalina.bat in {configured home}/bin directory.
