### ISSUE TITLE
No Tomcat instances are configured. Configure one as per https://marketplace.visualstudio.com/items?itemName=SnehalJha.local-tomcat#extesion-settings

### ISSUE THREAD

**Issue by tanu0303mnnit** [snehaljha/local-tomcat#12]

**Comment by snehaljha** [comment]
Can you provide more details related to directory you've configured

**Comment by fp024** [comment]
hello.

I had the same problem.

After installing the "local-tomcat" extension for the first time, when I edited the settings.json directly. I got a message like that.

I quit and restarted VSCode, and it worked.

**Comment by snehaljha** [comment]
It makes sense as settings are loaded with the startup. Closing this since it doesn't look like an issue.

**Comment by dozer47528** [comment]
same problem, I need to reload the config by restart vscode
