### ISSUE TITLE
How open context window?

### ISSUE THREAD

**Issue by VictorTrumpel** [snehaljha/local-tomcat#13]
How i can open this context window?
<img width="480" alt="Screenshot 2023-05-24 at 18 01 43" src="https://github.com/snehaljha/local-tomcat/assets/59663275/d5e81938-fc09-4542-868f-fcd5e39ed4e8">

**Comment by snehaljha** [comment]
ctrl+shift+P (default shortcut), you can type 'LT:' to list all the commands for this extension
