### ISSUE TITLE
Debug - LT: Run Tomcat in Debug Mode - Will run the tomcat in debug mode in its configured port if its not already running

### ISSUE THREAD

**Issue by rkumarnrtc** [snehaljha/local-tomcat#14]
I could install & configure & run tomcat and the app launched fine .
However when I run in Debug mode, the tomcat server starts , but how / where  do I debug ?
 How is the debug console launched ?
 All the breakpoints are getting ignored

**Comment by snehaljha** [comment]
The mentioned command just runs the tomcat in debug mode in it's designated port. You need to configure launch.json for debugging
